modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional

description='''${mod_description}'''
issueTrackerURL="https://github.com/pedroksl/AdvancedAE/issues"
displayURL="https://github.com/pedroksl/AdvanceddAE"
credits="Sea_Kerman for models"
logoFile="logo.png"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ae2"
    mandatory=true
    versionRange="[15.4.9,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ae2wtlib"
    mandatory=false
    versionRange="[15.3.0,)"
    ordering="AFTER"
    side="BOTH"